export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = `${SIGN_UP}_SUCCESS`;
export const SIGN_UP_FAILURE = `${SIGN_UP}_FAILURE`;

export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = `${SIGN_IN}_SUCCESS`;
export const SIGN_IN_FAILURE = `${SIGN_IN}_FAILURE`;

export const BUY_SOAT = 'BUY_SOAT';
export const BUY_SOAT_SUCCESS = `${BUY_SOAT}_SUCCESS`;
export const BUY_SOAT_FAILURE = `${BUY_SOAT}_FAILURE`;

export const SAVE_SECURE_SELECTED = 'SAVE_SECURE_SELECTED';
export const SAVE_SECURE_SELECTED_SUCCESS = `${SAVE_SECURE_SELECTED}_SUCCESS`;
export const SAVE_SECURE_SELECTED_FAILURE = `${SAVE_SECURE_SELECTED}_FAILURE`;


export const SECURE_CAR = 'SECURE_CAR';
export const SECURE_CAR_SUCCESS = `${SECURE_CAR}_SUCCESS`;
export const SECURE_CAR_FAILURE = `${SECURE_CAR}_FAILURE`;

export const CLIENT_INFO = 'CLIENT_INFO';
export const CLIENT_INFO_SUCCESS = `${CLIENT_INFO}_SUCCESS`;
export const CLIENT_INFO_FAILURE = `${CLIENT_INFO}_FAILURE`;

export const VEHICLE_INFO = 'VEHICLE_INFO';
export const VEHICLE_INFO_SUCCESS = `${VEHICLE_INFO}_SUCCESS`;
export const VEHICLE_INFO_FAILURE = `${VEHICLE_INFO}_FAILURE`;

export const BUY_SOAT_FORM = 'BUY_SOAT_FORM';
export const BUY_SOAT_FORM_SUCCESS = `${BUY_SOAT_FORM}_SUCCESS`;
export const BUY_SOAT_FORM_FAILURE = `${BUY_SOAT_FORM}_FAILURE`;

export const MAIN_INFO = 'MAIN_INFO';
export const MAIN_INFO_SUCCESS = `${MAIN_INFO}_SUCCESS`;
export const MAIN_INFO_FAILURE = `${MAIN_INFO}_FAILURE`;

export const GET_CITIES = 'GET_CITIES';
export const GET_CITIES_SUCCESS = `${GET_CITIES}_SUCCESS`;
export const GET_CITIES_FAILURE = `${GET_CITIES}_FAILURE`;

export const CREATE_COUNTRY = 'CREATE_COUNTRY';
export const CREATE_COUNTRY_SUCCESS = `${CREATE_COUNTRY}_SUCCESS`;
export const CREATE_COUNTRY_FAILURE = `${CREATE_COUNTRY}_FAILURE`;

export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRIES_SUCCESS = `${GET_COUNTRIES}_SUCCESS`;
export const GET_COUNTRIES_FAILURE = `${GET_COUNTRIES}_FAILURE`;

export const UPDATE_COUNTRY = 'UPDATE_COUNTRY';
export const UPDATE_COUNTRY_SUCCESS = `${UPDATE_COUNTRY}_SUCCESS`;
export const UPDATE_COUNTRY_FAILURE = `${UPDATE_COUNTRY}_FAILURE`;

export const DELETE_COUNTRY = 'DELETE_COUNTRY';
export const DELETE_COUNTRY_SUCCESS = `${DELETE_COUNTRY}_SUCCESS`;
export const DELETE_COUNTRY_FAILURE = `${DELETE_COUNTRY}_FAILURE`;

export const GET_COUNTRY_BY_ID = "GET_COUNTRY_BY_ID";
export const GET_COUNTRY_BY_ID_SUCCESS = `${GET_COUNTRY_BY_ID}_SUCCESS`;
export const GET_COUNTRY_BY_ID_FAILURE = `${GET_COUNTRY_BY_ID}_FAILURE`;

