export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = `${SIGN_UP}_SUCCESS`;
export const SIGN_UP_FAILURE = `${SIGN_UP}_FAILURE`;

export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_SUCCESS = `${SIGN_IN}_SUCCESS`;
export const SIGN_IN_FAILURE = `${SIGN_IN}_FAILURE`;

export const BUY_SOAT = 'BUY_SOAT';
export const BUY_SOAT_SUCCESS = `${BUY_SOAT}_SUCCESS`;
export const BUY_SOAT_FAILURE = `${BUY_SOAT}_FAILURE`;

export const SECURE_CAR = 'SECURE_CAR';
export const SECURE_CAR_SUCCESS = `${SECURE_CAR}_SUCCESS`;
export const SECURE_CAR_FAILURE = `${SECURE_CAR}_FAILURE`;

export const CLIENT_INFO = 'CLIENT_INFO';
export const CLIENT_INFO_SUCCESS = `${CLIENT_INFO}_SUCCESS`;
export const CLIENT_INFO_FAILURE = `${CLIENT_INFO}_FAILURE`;

export const VEHICLE_INFO = 'VEHICLE_INFO';
export const VEHICLE_INFO_SUCCESS = `${VEHICLE_INFO}_SUCCESS`;
export const VEHICLE_INFO_FAILURE = `${VEHICLE_INFO}_FAILURE`;

export const BUY_SOAT_FORM = 'BUY_SOAT_FORM';
export const BUY_SOAT_FORM_SUCCESS = `${BUY_SOAT_FORM}_SUCCESS`;
export const BUY_SOAT_FORM_FAILURE = `${BUY_SOAT_FORM}_FAILURE`;

export const MAIN_INFO = 'MAIN_INFO';
export const MAIN_INFO_SUCCESS = `${MAIN_INFO}_SUCCESS`;
export const MAIN_INFO_FAILURE = `${MAIN_INFO}_FAILURE`;

export const GET_CITIES = 'GET_CITIES';
export const GET_CITIES_SUCCESS = `${GET_CITIES}_SUCCESS`;
export const GET_CITIES_FAILURE = `${GET_CITIES}_FAILURE`;

export const CREATE_COUNTRY = 'CREATE_COUNTRY';
export const CREATE_COUNTRY_SUCCESS = `${CREATE_COUNTRY}_SUCCESS`;
export const CREATE_COUNTRY_FAILURE = `${CREATE_COUNTRY}_FAILURE`;

export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRIES_SUCCESS = `${GET_COUNTRIES}_SUCCESS`;
export const GET_COUNTRIES_FAILURE = `${GET_COUNTRIES}_FAILURE`;

export const UPDATE_COUNTRY = 'UPDATE_COUNTRY';
export const UPDATE_COUNTRY_SUCCESS = `${UPDATE_COUNTRY}_SUCCESS`;
export const UPDATE_COUNTRY_FAILURE = `${UPDATE_COUNTRY}_FAILURE`;

export const DELETE_COUNTRY = 'DELETE_COUNTRY';
export const DELETE_COUNTRY_SUCCESS = `${DELETE_COUNTRY}_SUCCESS`;
export const DELETE_COUNTRY_FAILURE = `${DELETE_COUNTRY}_FAILURE`;

export const GET_COUNTRY_BY_ID = "GET_COUNTRY_BY_ID";
export const GET_COUNTRY_BY_ID_SUCCESS = `${GET_COUNTRY_BY_ID}_SUCCESS`;
export const GET_COUNTRY_BY_ID_FAILURE = `${GET_COUNTRY_BY_ID}_FAILURE`;

/**
 * MAINACTIVITIES
 */
export const CREATE_MAINACTIVITY = 'CREATE_MAINACTIVITY';
export const CREATE_MAINACTIVITY_SUCCESS = `${CREATE_MAINACTIVITY}_SUCCESS`;
export const CREATE_MAINACTIVITY_FAILURE = `${CREATE_MAINACTIVITY}_FAILURE`;

export const GET_MAINACTIVITIES = 'GET_MAINACTIVITIES';
export const GET_MAINACTIVITIES_SUCCESS = `${GET_MAINACTIVITIES}_SUCCESS`;
export const GET_MAINACTIVITIES_FAILURE = `${GET_MAINACTIVITIES}_FAILURE`;

export const UPDATE_MAINACTIVITY = 'UPDATE_MAINACTIVITY';
export const UPDATE_MAINACTIVITY_SUCCESS = `${UPDATE_MAINACTIVITY}_SUCCESS`;
export const UPDATE_MAINACTIVITY_FAILURE = `${UPDATE_MAINACTIVITY}_FAILURE`;

export const DELETE_MAINACTIVITY = 'DELETE_MAINACTIVITY';
export const DELETE_MAINACTIVITY_SUCCESS = `${DELETE_MAINACTIVITY}_SUCCESS`;
export const DELETE_MAINACTIVITY_FAILURE = `${DELETE_MAINACTIVITY}_FAILURE`;

export const GET_MAINACTIVITY_BY_ID = "GET_MAINACTIVITY_BY_ID";
export const GET_MAINACTIVITY_BY_ID_SUCCESS = `${GET_MAINACTIVITY_BY_ID}_SUCCESS`;
export const GET_MAINACTIVITY_BY_ID_FAILURE = `${GET_MAINACTIVITY_BY_ID}_FAILURE`;

/**
 * MEDIUMRESPONSES
 */
export const CREATE_MEDIUMRESPONSES = 'CREATE_MEDIUMRESPONSES';
export const CREATE_MEDIUMRESPONSES_SUCCESS = `${CREATE_MEDIUMRESPONSES}_SUCCESS`;
export const CREATE_MEDIUMRESPONSES_FAILURE = `${CREATE_MEDIUMRESPONSES}_FAILURE`;

export const GET_MEDIUMRESPONSES = 'GET_MEDIUMRESPONSES';
export const GET_MEDIUMRESPONSES_SUCCESS = `${GET_MEDIUMRESPONSES}_SUCCESS`;
export const GET_MEDIUMRESPONSES_FAILURE = `${GET_MEDIUMRESPONSES}_FAILURE`;

export const UPDATE_MEDIUMRESPONSES = 'UPDATE_MEDIUMRESPONSES';
export const UPDATE_MEDIUMRESPONSES_SUCCESS = `${UPDATE_MEDIUMRESPONSES}_SUCCESS`;
export const UPDATE_MEDIUMRESPONSES_FAILURE = `${UPDATE_MEDIUMRESPONSES}_FAILURE`;

export const DELETE_MEDIUMRESPONSES = 'DELETE_MEDIUMRESPONSES';
export const DELETE_MEDIUMRESPONSES_SUCCESS = `${DELETE_MEDIUMRESPONSES}_SUCCESS`;
export const DELETE_MEDIUMRESPONSES_FAILURE = `${DELETE_MEDIUMRESPONSES}_FAILURE`;

export const GET_MEDIUMRESPONSES_BY_ID = "GET_MEDIUMRESPONSES_BY_ID";
export const GET_MEDIUMRESPONSES_BY_ID_SUCCESS = `${GET_MEDIUMRESPONSES_BY_ID}_SUCCESS`;
export const GET_MEDIUMRESPONSES_BY_ID_FAILURE = `${GET_MEDIUMRESPONSES_BY_ID}_FAILURE`;

/**
 * LINKCLASSES
 */
export const CREATE_LINKCLASSES = 'CREATE_LINKCLASSES';
export const CREATE_LINKCLASSES_SUCCESS = `${CREATE_LINKCLASSES}_SUCCESS`;
export const CREATE_LINKCLASSES_FAILURE = `${CREATE_LINKCLASSES}_FAILURE`;

export const GET_LINKCLASSES = 'GET_LINKCLASSES';
export const GET_LINKCLASSES_SUCCESS = `${GET_LINKCLASSES}_SUCCESS`;
export const GET_LINKCLASSES_FAILURE = `${GET_LINKCLASSES}_FAILURE`;

export const UPDATE_LINKCLASSES = 'UPDATE_LINKCLASSES';
export const UPDATE_LINKCLASSES_SUCCESS = `${UPDATE_LINKCLASSES}_SUCCESS`;
export const UPDATE_LINKCLASSES_FAILURE = `${UPDATE_LINKCLASSES}_FAILURE`;

export const DELETE_LINKCLASSES = 'DELETE_LINKCLASSES';
export const DELETE_LINKCLASSES_SUCCESS = `${DELETE_LINKCLASSES}_SUCCESS`;
export const DELETE_LINKCLASSES_FAILURE = `${DELETE_LINKCLASSES}_FAILURE`;

export const GET_LINKCLASSES_BY_ID = "GET_LINKCLASSES_BY_ID";
export const GET_LINKCLASSES_BY_ID_SUCCESS = `${GET_LINKCLASSES_BY_ID}_SUCCESS`;
export const GET_LINKCLASSES_BY_ID_FAILURE = `${GET_LINKCLASSES_BY_ID}_FAILURE`;

/**
 * PQRCONTACTS
 */
export const CREATE_PQRCONTACTS = 'CREATE_PQRCONTACTS';
export const CREATE_PQRCONTACTS_SUCCESS = `${CREATE_PQRCONTACTS}_SUCCESS`;
export const CREATE_PQRCONTACTS_FAILURE = `${CREATE_PQRCONTACTS}_FAILURE`;

export const GET_PQRCONTACTS = 'GET_PQRCONTACTS';
export const GET_PQRCONTACTS_SUCCESS = `${GET_PQRCONTACTS}_SUCCESS`;
export const GET_PQRCONTACTS_FAILURE = `${GET_PQRCONTACTS}_FAILURE`;

export const UPDATE_PQRCONTACTS = 'UPDATE_PQRCONTACTS';
export const UPDATE_PQRCONTACTS_SUCCESS = `${UPDATE_PQRCONTACTS}_SUCCESS`;
export const UPDATE_PQRCONTACTS_FAILURE = `${UPDATE_PQRCONTACTS}_FAILURE`;

export const DELETE_PQRCONTACTS = 'DELETE_PQRCONTACTS';
export const DELETE_PQRCONTACTS_SUCCESS = `${DELETE_PQRCONTACTS}_SUCCESS`;
export const DELETE_PQRCONTACTS_FAILURE = `${DELETE_PQRCONTACTS}_FAILURE`;

export const GET_PQRCONTACTS_BY_ID = "GET_PQRCONTACTS_BY_ID";
export const GET_PQRCONTACTS_BY_ID_SUCCESS = `${GET_PQRCONTACTS_BY_ID}_SUCCESS`;
export const GET_PQRCONTACTS_BY_ID_FAILURE = `${GET_PQRCONTACTS_BY_ID}_FAILURE`;

/**
 * TYPEACTIVITIES
 */
export const CREATE_TYPEACTIVITY = 'CREATE_TYPEACTIVITY';
export const CREATE_TYPEACTIVITY_SUCCESS = `${CREATE_TYPEACTIVITY}_SUCCESS`;
export const CREATE_TYPEACTIVITY_FAILURE = `${CREATE_TYPEACTIVITY}_FAILURE`;

export const GET_TYPEACTIVITIES = 'GET_TYPEACTIVITIES';
export const GET_TYPEACTIVITIES_SUCCESS = `${GET_TYPEACTIVITIES}_SUCCESS`;
export const GET_TYPEACTIVITIES_FAILURE = `${GET_TYPEACTIVITIES}_FAILURE`;

export const UPDATE_TYPEACTIVITY = 'UPDATE_TYPEACTIVITY';
export const UPDATE_TYPEACTIVITY_SUCCESS = `${UPDATE_TYPEACTIVITY}_SUCCESS`;
export const UPDATE_TYPEACTIVITY_FAILURE = `${UPDATE_TYPEACTIVITY}_FAILURE`;

export const DELETE_TYPEACTIVITY = 'DELETE_TYPEACTIVITY';
export const DELETE_TYPEACTIVITY_SUCCESS = `${DELETE_TYPEACTIVITY}_SUCCESS`;
export const DELETE_TYPEACTIVITY_FAILURE = `${DELETE_TYPEACTIVITY}_FAILURE`;

export const GET_TYPEACTIVITY_BY_ID = "GET_TYPEACTIVITY_BY_ID";
export const GET_TYPEACTIVITY_BY_ID_SUCCESS = `${GET_TYPEACTIVITY_BY_ID}_SUCCESS`;
export const GET_TYPEACTIVITY_BY_ID_FAILURE = `${GET_TYPEACTIVITY_BY_ID}_FAILURE`;

/**
 * PRODUCTS
 */
export const CREATE_PRODUCTS = 'CREATE_PRODUCTS';
export const CREATE_PRODUCTS_SUCCESS = `${CREATE_PRODUCTS}_SUCCESS`;
export const CREATE_PRODUCTS_FAILURE = `${CREATE_PRODUCTS}_FAILURE`;

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = `${GET_PRODUCTS}_SUCCESS`;
export const GET_PRODUCTS_FAILURE = `${GET_PRODUCTS}_FAILURE`;

export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';
export const UPDATE_PRODUCTS_SUCCESS = `${UPDATE_PRODUCTS}_SUCCESS`;
export const UPDATE_PRODUCTS_FAILURE = `${UPDATE_PRODUCTS}_FAILURE`;

export const DELETE_PRODUCTS = 'DELETE_PRODUCTS';
export const DELETE_PRODUCTS_SUCCESS = `${DELETE_PRODUCTS}_SUCCESS`;
export const DELETE_PRODUCTS_FAILURE = `${DELETE_PRODUCTS}_FAILURE`;

export const GET_PRODUCTS_BY_ID = "GET_PRODUCTS_BY_ID";
export const GET_PRODUCTS_BY_ID_SUCCESS = `${GET_PRODUCTS_BY_ID}_SUCCESS`;
export const GET_PRODUCTS_BY_ID_FAILURE = `${GET_PRODUCTS_BY_ID}_FAILURE`;

/**
 * INSURERS
 */
export const CREATE_INSURERS = 'CREATE_INSURERS';
export const CREATE_INSURERS_SUCCESS = `${CREATE_INSURERS}_SUCCESS`;
export const CREATE_INSURERS_FAILURE = `${CREATE_INSURERS}_FAILURE`;

export const GET_INSURERS = 'GET_INSURERS';
export const GET_INSURERS_SUCCESS = `${GET_INSURERS}_SUCCESS`;
export const GET_INSURERS_FAILURE = `${GET_INSURERS}_FAILURE`;

export const UPDATE_INSURERS = 'UPDATE_INSURERS';
export const UPDATE_INSURERS_SUCCESS = `${UPDATE_INSURERS}_SUCCESS`;
export const UPDATE_INSURERS_FAILURE = `${UPDATE_INSURERS}_FAILURE`;

export const DELETE_INSURERS = 'DELETE_INSURERS';
export const DELETE_INSURERS_SUCCESS = `${DELETE_INSURERS}_SUCCESS`;
export const DELETE_INSURERS_FAILURE = `${DELETE_INSURERS}_FAILURE`;

export const GET_INSURERS_BY_ID = "GET_INSURERS_BY_ID";
export const GET_INSURERS_BY_ID_SUCCESS = `${GET_INSURERS_BY_ID}_SUCCESS`;
export const GET_INSURERS_BY_ID_FAILURE = `${GET_INSURERS_BY_ID}_FAILURE`;

/**
 * TYPEOPERATIONS
 */
export const CREATE_TYPEOPERATIONS = 'CREATE_TYPEOPERATIONS';
export const CREATE_TYPEOPERATIONS_SUCCESS = `${CREATE_TYPEOPERATIONS}_SUCCESS`;
export const CREATE_TYPEOPERATIONS_FAILURE = `${CREATE_TYPEOPERATIONS}_FAILURE`;

export const GET_TYPEOPERATIONS = 'GET_TYPEOPERATIONS';
export const GET_TYPEOPERATIONS_SUCCESS = `${GET_TYPEOPERATIONS}_SUCCESS`;
export const GET_TYPEOPERATIONS_FAILURE = `${GET_TYPEOPERATIONS}_FAILURE`;

export const UPDATE_TYPEOPERATIONS = 'UPDATE_TYPEOPERATIONS';
export const UPDATE_TYPEOPERATIONS_SUCCESS = `${UPDATE_TYPEOPERATIONS}_SUCCESS`;
export const UPDATE_TYPEOPERATIONS_FAILURE = `${UPDATE_TYPEOPERATIONS}_FAILURE`;

export const DELETE_TYPEOPERATIONS = 'DELETE_TYPEOPERATIONS';
export const DELETE_TYPEOPERATIONS_SUCCESS = `${DELETE_TYPEOPERATIONS}_SUCCESS`;
export const DELETE_TYPEOPERATIONS_FAILURE = `${DELETE_TYPEOPERATIONS}_FAILURE`;

export const GET_TYPEOPERATIONS_BY_ID = "GET_TYPEOPERATIONS_BY_ID";
export const GET_TYPEOPERATIONS_BY_ID_SUCCESS = `${GET_TYPEOPERATIONS_BY_ID}_SUCCESS`;
export const GET_TYPEOPERATIONS_BY_ID_FAILURE = `${GET_TYPEOPERATIONS_BY_ID}_FAILURE`;

/**
 * TYPEINDUSTRIES
 */
export const CREATE_TYPEINDUSTRIES = 'CREATE_TYPEINDUSTRIES';
export const CREATE_TYPEINDUSTRIES_SUCCESS = `${CREATE_TYPEINDUSTRIES}_SUCCESS`;
export const CREATE_TYPEINDUSTRIES_FAILURE = `${CREATE_TYPEINDUSTRIES}_FAILURE`;

export const GET_TYPEINDUSTRIES = 'GET_TYPEINDUSTRIES';
export const GET_TYPEINDUSTRIES_SUCCESS = `${GET_TYPEINDUSTRIES}_SUCCESS`;
export const GET_TYPEINDUSTRIES_FAILURE = `${GET_TYPEINDUSTRIES}_FAILURE`;

export const UPDATE_TYPEINDUSTRIES = 'UPDATE_TYPEINDUSTRIES';
export const UPDATE_TYPEINDUSTRIES_SUCCESS = `${UPDATE_TYPEINDUSTRIES}_SUCCESS`;
export const UPDATE_TYPEINDUSTRIES_FAILURE = `${UPDATE_TYPEINDUSTRIES}_FAILURE`;

export const DELETE_TYPEINDUSTRIES = 'DELETE_TYPEINDUSTRIES';
export const DELETE_TYPEINDUSTRIES_SUCCESS = `${DELETE_TYPEINDUSTRIES}_SUCCESS`;
export const DELETE_TYPEINDUSTRIES_FAILURE = `${DELETE_TYPEINDUSTRIES}_FAILURE`;

export const GET_TYPEINDUSTRIES_BY_ID = "GET_TYPEINDUSTRIES_BY_ID";
export const GET_TYPEINDUSTRIES_BY_ID_SUCCESS = `${GET_TYPEINDUSTRIES_BY_ID}_SUCCESS`;
export const GET_TYPEINDUSTRIES_BY_ID_FAILURE = `${GET_TYPEINDUSTRIES_BY_ID}_FAILURE`;

/**
 * TYPEIDENTIFICATIONS
 */
export const CREATE_TYPEIDENTIFICATIONS = 'CREATE_TYPEIDENTIFICATIONS';
export const CREATE_TYPEIDENTIFICATIONS_SUCCESS = `${CREATE_TYPEIDENTIFICATIONS}_SUCCESS`;
export const CREATE_TYPEIDENTIFICATIONS_FAILURE = `${CREATE_TYPEIDENTIFICATIONS}_FAILURE`;

export const GET_TYPEIDENTIFICATIONS = 'GET_TYPEIDENTIFICATIONS';
export const GET_TYPEIDENTIFICATIONS_SUCCESS = `${GET_TYPEIDENTIFICATIONS}_SUCCESS`;
export const GET_TYPEIDENTIFICATIONS_FAILURE = `${GET_TYPEIDENTIFICATIONS}_FAILURE`;

export const UPDATE_TYPEIDENTIFICATIONS = 'UPDATE_TYPEIDENTIFICATIONS';
export const UPDATE_TYPEIDENTIFICATIONS_SUCCESS = `${UPDATE_TYPEIDENTIFICATIONS}_SUCCESS`;
export const UPDATE_TYPEIDENTIFICATIONS_FAILURE = `${UPDATE_TYPEIDENTIFICATIONS}_FAILURE`;

export const DELETE_TYPEIDENTIFICATIONS = 'DELETE_TYPEIDENTIFICATIONS';
export const DELETE_TYPEIDENTIFICATIONS_SUCCESS = `${DELETE_TYPEIDENTIFICATIONS}_SUCCESS`;
export const DELETE_TYPEIDENTIFICATIONS_FAILURE = `${DELETE_TYPEIDENTIFICATIONS}_FAILURE`;

export const GET_TYPEIDENTIFICATIONS_BY_ID = "GET_TYPEIDENTIFICATIONS_BY_ID";
export const GET_TYPEIDENTIFICATIONS_BY_ID_SUCCESS = `${GET_TYPEIDENTIFICATIONS_BY_ID}_SUCCESS`;
export const GET_TYPEIDENTIFICATIONS_BY_ID_FAILURE = `${GET_TYPEIDENTIFICATIONS_BY_ID}_FAILURE`;

/**
 * TYPECOMPANIES
 */
export const CREATE_TYPECOMPANIES = 'CREATE_TYPECOMPANIES';
export const CREATE_TYPECOMPANIES_SUCCESS = `${CREATE_TYPECOMPANIES}_SUCCESS`;
export const CREATE_TYPECOMPANIES_FAILURE = `${CREATE_TYPECOMPANIES}_FAILURE`;

export const GET_TYPECOMPANIES = 'GET_TYPECOMPANIES';
export const GET_TYPECOMPANIES_SUCCESS = `${GET_TYPECOMPANIES}_SUCCESS`;
export const GET_TYPECOMPANIES_FAILURE = `${GET_TYPECOMPANIES}_FAILURE`;

export const UPDATE_TYPECOMPANIES = 'UPDATE_TYPECOMPANIES';
export const UPDATE_TYPECOMPANIES_SUCCESS = `${UPDATE_TYPECOMPANIES}_SUCCESS`;
export const UPDATE_TYPECOMPANIES_FAILURE = `${UPDATE_TYPECOMPANIES}_FAILURE`;

export const DELETE_TYPECOMPANIES = 'DELETE_TYPECOMPANIES';
export const DELETE_TYPECOMPANIES_SUCCESS = `${DELETE_TYPECOMPANIES}_SUCCESS`;
export const DELETE_TYPECOMPANIES_FAILURE = `${DELETE_TYPECOMPANIES}_FAILURE`;

export const GET_TYPECOMPANIES_BY_ID = "GET_TYPECOMPANIES_BY_ID";
export const GET_TYPECOMPANIES_BY_ID_SUCCESS = `${GET_TYPECOMPANIES_BY_ID}_SUCCESS`;
export const GET_TYPECOMPANIES_BY_ID_FAILURE = `${GET_TYPECOMPANIES_BY_ID}_FAILURE`;

/**
 * REQUESTTYPES
 */
export const CREATE_REQUESTTYPES = 'CREATE_REQUESTTYPES';
export const CREATE_REQUESTTYPES_SUCCESS = `${CREATE_REQUESTTYPES}_SUCCESS`;
export const CREATE_REQUESTTYPES_FAILURE = `${CREATE_REQUESTTYPES}_FAILURE`;

export const GET_REQUESTTYPES = 'GET_REQUESTTYPES';
export const GET_REQUESTTYPES_SUCCESS = `${GET_REQUESTTYPES}_SUCCESS`;
export const GET_REQUESTTYPES_FAILURE = `${GET_REQUESTTYPES}_FAILURE`;

export const UPDATE_REQUESTTYPES = 'UPDATE_REQUESTTYPES';
export const UPDATE_REQUESTTYPES_SUCCESS = `${UPDATE_REQUESTTYPES}_SUCCESS`;
export const UPDATE_REQUESTTYPES_FAILURE = `${UPDATE_REQUESTTYPES}_FAILURE`;

export const DELETE_REQUESTTYPES = 'DELETE_REQUESTTYPES';
export const DELETE_REQUESTTYPES_SUCCESS = `${DELETE_REQUESTTYPES}_SUCCESS`;
export const DELETE_REQUESTTYPES_FAILURE = `${DELETE_REQUESTTYPES}_FAILURE`;

export const GET_REQUESTTYPES_BY_ID = "GET_REQUESTTYPES_BY_ID";
export const GET_REQUESTTYPES_BY_ID_SUCCESS = `${GET_REQUESTTYPES_BY_ID}_SUCCESS`;
export const GET_REQUESTTYPES_BY_ID_FAILURE = `${GET_REQUESTTYPES_BY_ID}_FAILURE`;

/**
 * SHARSPRING
 */
export const IDLEADSHARP = 'IDLEADSHARP';
export const IDLEADSHARP_SUCCESS = `${IDLEADSHARP}_SUCCESS`;
export const IDLEADSHARP_FAILURE = `${IDLEADSHARP}_FAILURE`;