import { LOG_OUT_MOVEMENT } from '../../movements/constants';
import { GET_BRAND_SUCCESS } from '../../sagas/brands/constants';
import { GET_BRIEF_SUCCESS } from '../../sagas/briefs/constants';
import {
  APPROVE_ACTIVE_PROPOSAL_SUCCESS,
  BIND_CAMPAIGN_CONTENT_SUCCESS,
  CREATE_COMMENT_ACTIVE_PROPOSAL_SUCCESS,
  CREATE_COMMENT_CONTENT_ACTIVE_PROPOSAL_SUCCESS,
  SHOW_ACTIVE_PROPOSAL_SUCCESS,
  SHOW_CAMPAIGN_CONTENT_GRID_SUCCESS,
  SHOW_CAMPAIGN_CONTENT_SUCCESS,
  SHOW_CAMPAIGN_PROPOSAL_PREVIEW_SUCCESS,
  SHOW_CAMPAIGN_PROPOSAL_SUCCESS,
  SHOW_CAMPAIGN_SUCCESS,
  UPDATE_CONTENT_ACTIVE_PROPOSAL_STATUS_SUCCESS,
  UPDATE_PROPOSAL_STATUS_SUCCESS,
  SHOW_CAMPAIGN_REPORT_SUCCESS,
} from '../../sagas/campaigns/constants';
import { SHOW_SNA_SUCCESS } from '../../sagas/socialNetworkAccounts/constants';
import { SHOW_SNT_SUCCESS } from '../../sagas/socialNetworkTraces/constants';
import {
  SHOW_USER_SUCCESS,
  UPDATE_USER_SUCCESS,
} from '../../sagas/users/constants';

export const INITIAL_STATE = null;

export default (state = INITIAL_STATE, { type, payload }) => {
  switch (type) {
    case GET_BRAND_SUCCESS:
    case SHOW_SNA_SUCCESS:
    case SHOW_SNT_SUCCESS:
    case GET_BRIEF_SUCCESS:
    case SHOW_CAMPAIGN_SUCCESS:
    case SHOW_ACTIVE_PROPOSAL_SUCCESS:
    case SHOW_CAMPAIGN_PROPOSAL_PREVIEW_SUCCESS:
    case SHOW_CAMPAIGN_PROPOSAL_SUCCESS:
    case APPROVE_ACTIVE_PROPOSAL_SUCCESS:
    case UPDATE_PROPOSAL_STATUS_SUCCESS:
    case CREATE_COMMENT_ACTIVE_PROPOSAL_SUCCESS:
    case SHOW_CAMPAIGN_CONTENT_SUCCESS:
    case SHOW_CAMPAIGN_CONTENT_GRID_SUCCESS:
    case SHOW_USER_SUCCESS:
    case UPDATE_USER_SUCCESS:
    case SHOW_CAMPAIGN_REPORT_SUCCESS:
      return { ...payload };
    case UPDATE_CONTENT_ACTIVE_PROPOSAL_STATUS_SUCCESS:
    case CREATE_COMMENT_CONTENT_ACTIVE_PROPOSAL_SUCCESS:
    case BIND_CAMPAIGN_CONTENT_SUCCESS:
      return state;
    case LOG_OUT_MOVEMENT:
    case '@@router/LOCATION_CHANGE':
      return INITIAL_STATE;
    default:
      return state;
  }
};
