export const CREATE_COUNTRY = 'CREATE_COUNTRY';
export const CREATE_COUNTRY_SUCCESS = `${CREATE_COUNTRY}_SUCCESS`;
export const CREATE_COUNTRY_FAILURE = `${CREATE_COUNTRY}_FAILURE`;

export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRIES_SUCCESS = `${GET_COUNTRIES}_SUCCESS`;
export const GET_COUNTRIES_FAILURE = `${GET_COUNTRIES}_FAILURE`;

export const UPDATE_COUNTRY = 'UPDATE_COUNTRY';
export const UPDATE_COUNTRY_SUCCESS = `${UPDATE_COUNTRY}_SUCCESS`;
export const UPDATE_COUNTRY_FAILURE = `${UPDATE_COUNTRY}_FAILURE`;

export const DELETE_COUNTRY = 'DELETE_COUNTRY';
export const DELETE_COUNTRY_SUCCESS = `${DELETE_COUNTRY}_SUCCESS`;
export const DELETE_COUNTRY_FAILURE = `${DELETE_COUNTRY}_FAILURE`;

export const GET_COUNTRY_BY_ID = "GET_COUNTRY_BY_ID";
export const GET_COUNTRY_BY_ID_SUCCESS = `${GET_COUNTRY_BY_ID}_SUCCESS`;
export const GET_COUNTRY_BY_ID_FAILURE = `${GET_COUNTRY_BY_ID}_FAILURE`;
